version: '3'

services:
  frontend:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./servidor3
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mqttapp:
    build:
      context: ./Capture
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

  mongo:
    image: mrontendongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
